export const LOBE_THEME_APPEARANCE = 'IMOOGLE_THEME_APPEARANCE';

export const LOBE_THEME_PRIMARY_COLOR = 'IMOOGLE_THEME_PRIMARY_COLOR';

export const LOBE_THEME_NEUTRAL_COLOR = 'IMOOGLE_THEME_NEUTRAL_COLOR';
